### PR TITLE
fix broken import of MilliSatoshi

### PR DESCRIPTION
**Pull request by prusnak**
fixes https://github.com/lnbits/withdraw/issues/47

### CODE REVIEW

**Comment by prusnak** [comment]
the CI fails because we still have lnurl 0.4.x in lnbits dev :-)

**Comment by prusnak** [comment]
can you please merge this and release 0.1.12 so we can finally merge https://github.com/lnbits/lnbits/pull/2619

withdraw 0.1.11 will be compatible up to lnbits 0.12.10
withdraw 0.1.12 will be compatible from lnbits 0.12.11

**Comment by prusnak** [comment]
@dni can you please merge this and release 0.1.12 so we can finally merge https://github.com/lnbits/lnbits/pull/2619

withdraw 0.1.11 will be compatible up to lnbits 0.12.10
withdraw 0.1.12 will be compatible from lnbits 0.12.11

**Review by dni — APPROVED** [review]
sry

**Pull request merged**
