### PR TITLE
fix: update select query in get_withdraw_links

### PR DESCRIPTION
**Pull request by jimasuen**
**Bug:** The `api_links` function in views_api.py was returning an empty value for the `data` key despite returning the correct `total` value. 

**Solution:** Adding the `LIMIT` and `OFFSET` parameters to the select query in `get_withdraw_links` only when the limit is greater than 0 solves this issue.

### CODE REVIEW

**Comment by dni** [comment]
can you verify thats still the case for v1?

**Comment by jimasuen** [comment]
> can you verify thats still the case for v1?

It's still the same issue with v1.

**Comment by dni** [comment]
can you resolve the conflict?

**Comment by jimasuen** [comment]
> can you resolve the conflict?

working on it

**Comment by jimasuen** [comment]
> can you resolve the conflict?

Conflicts resolved

**Review by dni — APPROVED** [review]

**Comment by dni** [comment]
LGTM

**Review by motorina0 — APPROVED** [review]

**Comment by dni** [comment]
formatting seems to fail

**Comment by jimasuen** [comment]
> formatting seems to fail

reformatted the code

**Pull request merged**
